import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';

import SvgSprite from 'components/SvgSprite';

const skills = ['html', 'css', 'sass', 'tailwindcss', 'js', 'ts', 'react', 'redux', 'nextjs', 'git'];

const Home: NextPage = () => {
  return (
    <main>
      <Head>
        <title>Xuan&apos;s website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="py-32">
        <h1 className="text-center font-serif text-8xl capitalize">A front-end developer</h1>
      </header>

      <section className="py-4">
        <h2 className="mb-10 text-3xl font-semibold">Skills</h2>
        <div className="flex flex-wrap justify-center gap-10">
          {skills.map(skill => {
            return (
              <SvgSprite
                key={skill}
                category="skill"
                symbolId={`${skill}`}
                className="h-20 w-20 transition-transform hover:scale-125"
              >
                <title>{skill}</title>
              </SvgSprite>
            );
          })}
        </div>
      </section>
    </main>
  );
};

export default Home;
